// Code generated by go generate. DO NOT EDIT.
package gateway

import "cynthia/ds/payloads"
import "cynthia/ds/dsevents"


func (c *Client) OnHello(handler func(c *Client, p payloads.Hello)) {
	On(c, dsevents.Hello, handler)
}

func (c *Client) OnReady(handler func(c *Client, p payloads.Ready)) {
	On(c, dsevents.Ready, handler)
}

func (c *Client) OnResumed(handler func(c *Client, p payloads.Resumed)) {
	On(c, dsevents.Resumed, handler)
}

func (c *Client) OnReconnect(handler func(c *Client, p payloads.Reconnect)) {
	On(c, dsevents.Reconnect, handler)
}

func (c *Client) OnRateLimited(handler func(c *Client, p payloads.RateLimited)) {
	On(c, dsevents.RateLimited, handler)
}

func (c *Client) OnInvalidSession(handler func(c *Client, p payloads.InvalidSession)) {
	On(c, dsevents.InvalidSession, handler)
}

func (c *Client) OnApplicationCommandPermissionsUpdate(handler func(c *Client, p payloads.ApplicationCommandPermissionsUpdate)) {
	On(c, dsevents.ApplicationCommandPermissionsUpdate, handler)
}

func (c *Client) OnAutoModerationRuleCreate(handler func(c *Client, p payloads.AutoModerationRuleCreate)) {
	On(c, dsevents.AutoModerationRuleCreate, handler)
}

func (c *Client) OnAutoModerationRuleUpdate(handler func(c *Client, p payloads.AutoModerationRuleUpdate)) {
	On(c, dsevents.AutoModerationRuleUpdate, handler)
}

func (c *Client) OnAutoModerationRuleDelete(handler func(c *Client, p payloads.AutoModerationRuleDelete)) {
	On(c, dsevents.AutoModerationRuleDelete, handler)
}

func (c *Client) OnAutoModerationActionExecution(handler func(c *Client, p payloads.AutoModerationActionExecution)) {
	On(c, dsevents.AutoModerationActionExecution, handler)
}

func (c *Client) OnChannelCreate(handler func(c *Client, p payloads.ChannelCreate)) {
	On(c, dsevents.ChannelCreate, handler)
}

func (c *Client) OnChannelUpdate(handler func(c *Client, p payloads.ChannelUpdate)) {
	On(c, dsevents.ChannelUpdate, handler)
}

func (c *Client) OnChannelDelete(handler func(c *Client, p payloads.ChannelDelete)) {
	On(c, dsevents.ChannelDelete, handler)
}

func (c *Client) OnChannelInfo(handler func(c *Client, p payloads.ChannelInfo)) {
	On(c, dsevents.ChannelInfo, handler)
}

func (c *Client) OnChannelPinsUpdate(handler func(c *Client, p payloads.ChannelPinsUpdate)) {
	On(c, dsevents.ChannelPinsUpdate, handler)
}

func (c *Client) OnThreadCreate(handler func(c *Client, p payloads.ThreadCreate)) {
	On(c, dsevents.ThreadCreate, handler)
}

func (c *Client) OnThreadUpdate(handler func(c *Client, p payloads.ThreadUpdate)) {
	On(c, dsevents.ThreadUpdate, handler)
}

func (c *Client) OnThreadDelete(handler func(c *Client, p payloads.ThreadDelete)) {
	On(c, dsevents.ThreadDelete, handler)
}

func (c *Client) OnThreadListSync(handler func(c *Client, p payloads.ThreadListSync)) {
	On(c, dsevents.ThreadListSync, handler)
}

func (c *Client) OnThreadMemberUpdate(handler func(c *Client, p payloads.ThreadMemberUpdate)) {
	On(c, dsevents.ThreadMemberUpdate, handler)
}

func (c *Client) OnThreadMembersUpdate(handler func(c *Client, p payloads.ThreadMembersUpdate)) {
	On(c, dsevents.ThreadMembersUpdate, handler)
}

func (c *Client) OnEntitlementCreate(handler func(c *Client, p payloads.EntitlementCreate)) {
	On(c, dsevents.EntitlementCreate, handler)
}

func (c *Client) OnEntitlementUpdate(handler func(c *Client, p payloads.EntitlementUpdate)) {
	On(c, dsevents.EntitlementUpdate, handler)
}

func (c *Client) OnEntitlementDelete(handler func(c *Client, p payloads.EntitlementDelete)) {
	On(c, dsevents.EntitlementDelete, handler)
}

func (c *Client) OnGuildCreate(handler func(c *Client, p payloads.GuildCreate)) {
	On(c, dsevents.GuildCreate, handler)
}

func (c *Client) OnGuildUpdate(handler func(c *Client, p payloads.GuildUpdate)) {
	On(c, dsevents.GuildUpdate, handler)
}

func (c *Client) OnGuildDelete(handler func(c *Client, p payloads.GuildDelete)) {
	On(c, dsevents.GuildDelete, handler)
}

func (c *Client) OnGuildAuditLogEntryCreate(handler func(c *Client, p payloads.GuildAuditLogEntryCreate)) {
	On(c, dsevents.GuildAuditLogEntryCreate, handler)
}

func (c *Client) OnGuildBanAdd(handler func(c *Client, p payloads.GuildBanAdd)) {
	On(c, dsevents.GuildBanAdd, handler)
}

func (c *Client) OnGuildBanRemove(handler func(c *Client, p payloads.GuildBanRemove)) {
	On(c, dsevents.GuildBanRemove, handler)
}

func (c *Client) OnGuildEmojisUpdate(handler func(c *Client, p payloads.GuildEmojisUpdate)) {
	On(c, dsevents.GuildEmojisUpdate, handler)
}

func (c *Client) OnGuildStickersUpdate(handler func(c *Client, p payloads.GuildStickersUpdate)) {
	On(c, dsevents.GuildStickersUpdate, handler)
}

func (c *Client) OnGuildIntegrationsUpdate(handler func(c *Client, p payloads.GuildIntegrationsUpdate)) {
	On(c, dsevents.GuildIntegrationsUpdate, handler)
}

func (c *Client) OnGuildMemberAdd(handler func(c *Client, p payloads.GuildMemberAdd)) {
	On(c, dsevents.GuildMemberAdd, handler)
}

func (c *Client) OnGuildMemberRemove(handler func(c *Client, p payloads.GuildMemberRemove)) {
	On(c, dsevents.GuildMemberRemove, handler)
}

func (c *Client) OnGuildMemberUpdate(handler func(c *Client, p payloads.GuildMemberUpdate)) {
	On(c, dsevents.GuildMemberUpdate, handler)
}

func (c *Client) OnGuildMembersChunk(handler func(c *Client, p payloads.GuildMembersChunk)) {
	On(c, dsevents.GuildMembersChunk, handler)
}

func (c *Client) OnGuildRoleCreate(handler func(c *Client, p payloads.GuildRoleCreate)) {
	On(c, dsevents.GuildRoleCreate, handler)
}

func (c *Client) OnGuildRoleUpdate(handler func(c *Client, p payloads.GuildRoleUpdate)) {
	On(c, dsevents.GuildRoleUpdate, handler)
}

func (c *Client) OnGuildRoleDelete(handler func(c *Client, p payloads.GuildRoleDelete)) {
	On(c, dsevents.GuildRoleDelete, handler)
}

func (c *Client) OnGuildScheduledEventCreate(handler func(c *Client, p payloads.GuildScheduledEventCreate)) {
	On(c, dsevents.GuildScheduledEventCreate, handler)
}

func (c *Client) OnGuildScheduledEventUpdate(handler func(c *Client, p payloads.GuildScheduledEventUpdate)) {
	On(c, dsevents.GuildScheduledEventUpdate, handler)
}

func (c *Client) OnGuildScheduledEventDelete(handler func(c *Client, p payloads.GuildScheduledEventDelete)) {
	On(c, dsevents.GuildScheduledEventDelete, handler)
}

func (c *Client) OnGuildScheduledEventUserAdd(handler func(c *Client, p payloads.GuildScheduledEventUserAdd)) {
	On(c, dsevents.GuildScheduledEventUserAdd, handler)
}

func (c *Client) OnGuildScheduledEventUserRemove(handler func(c *Client, p payloads.GuildScheduledEventUserRemove)) {
	On(c, dsevents.GuildScheduledEventUserRemove, handler)
}

func (c *Client) OnGuildSoundboardSoundCreate(handler func(c *Client, p payloads.GuildSoundboardSoundCreate)) {
	On(c, dsevents.GuildSoundboardSoundCreate, handler)
}

func (c *Client) OnGuildSoundboardSoundUpdate(handler func(c *Client, p payloads.GuildSoundboardSoundUpdate)) {
	On(c, dsevents.GuildSoundboardSoundUpdate, handler)
}

func (c *Client) OnGuildSoundboardSoundDelete(handler func(c *Client, p payloads.GuildSoundboardSoundDelete)) {
	On(c, dsevents.GuildSoundboardSoundDelete, handler)
}

func (c *Client) OnGuildSoundboardSoundsUpdate(handler func(c *Client, p payloads.GuildSoundboardSoundsUpdate)) {
	On(c, dsevents.GuildSoundboardSoundsUpdate, handler)
}

func (c *Client) OnSoundboardSounds(handler func(c *Client, p payloads.SoundboardSounds)) {
	On(c, dsevents.SoundboardSounds, handler)
}

func (c *Client) OnIntegrationCreate(handler func(c *Client, p payloads.IntegrationCreate)) {
	On(c, dsevents.IntegrationCreate, handler)
}

func (c *Client) OnIntegrationUpdate(handler func(c *Client, p payloads.IntegrationUpdate)) {
	On(c, dsevents.IntegrationUpdate, handler)
}

func (c *Client) OnIntegrationDelete(handler func(c *Client, p payloads.IntegrationDelete)) {
	On(c, dsevents.IntegrationDelete, handler)
}

func (c *Client) OnInteractionCreate(handler func(c *Client, p payloads.InteractionCreate)) {
	On(c, dsevents.InteractionCreate, handler)
}

func (c *Client) OnInviteCreate(handler func(c *Client, p payloads.InviteCreate)) {
	On(c, dsevents.InviteCreate, handler)
}

func (c *Client) OnInviteDelete(handler func(c *Client, p payloads.InviteDelete)) {
	On(c, dsevents.InviteDelete, handler)
}

func (c *Client) OnMessageCreate(handler func(c *Client, p payloads.MessageCreate)) {
	On(c, dsevents.MessageCreate, handler)
}

func (c *Client) OnMessageUpdate(handler func(c *Client, p payloads.MessageUpdate)) {
	On(c, dsevents.MessageUpdate, handler)
}

func (c *Client) OnMessageDelete(handler func(c *Client, p payloads.MessageDelete)) {
	On(c, dsevents.MessageDelete, handler)
}

func (c *Client) OnMessageDeleteBulk(handler func(c *Client, p payloads.MessageDeleteBulk)) {
	On(c, dsevents.MessageDeleteBulk, handler)
}

func (c *Client) OnMessageReactionAdd(handler func(c *Client, p payloads.MessageReactionAdd)) {
	On(c, dsevents.MessageReactionAdd, handler)
}

func (c *Client) OnMessageReactionRemove(handler func(c *Client, p payloads.MessageReactionRemove)) {
	On(c, dsevents.MessageReactionRemove, handler)
}

func (c *Client) OnMessageReactionRemoveAll(handler func(c *Client, p payloads.MessageReactionRemoveAll)) {
	On(c, dsevents.MessageReactionRemoveAll, handler)
}

func (c *Client) OnMessageReactionRemoveEmoji(handler func(c *Client, p payloads.MessageReactionRemoveEmoji)) {
	On(c, dsevents.MessageReactionRemoveEmoji, handler)
}

func (c *Client) OnPresenceUpdate(handler func(c *Client, p payloads.PresenceUpdate)) {
	On(c, dsevents.PresenceUpdate, handler)
}

func (c *Client) OnStageInstanceCreate(handler func(c *Client, p payloads.StageInstanceCreate)) {
	On(c, dsevents.StageInstanceCreate, handler)
}

func (c *Client) OnStageInstanceUpdate(handler func(c *Client, p payloads.StageInstanceUpdate)) {
	On(c, dsevents.StageInstanceUpdate, handler)
}

func (c *Client) OnStageInstanceDelete(handler func(c *Client, p payloads.StageInstanceDelete)) {
	On(c, dsevents.StageInstanceDelete, handler)
}

func (c *Client) OnSubscriptionCreate(handler func(c *Client, p payloads.SubscriptionCreate)) {
	On(c, dsevents.SubscriptionCreate, handler)
}

func (c *Client) OnSubscriptionUpdate(handler func(c *Client, p payloads.SubscriptionUpdate)) {
	On(c, dsevents.SubscriptionUpdate, handler)
}

func (c *Client) OnSubscriptionDelete(handler func(c *Client, p payloads.SubscriptionDelete)) {
	On(c, dsevents.SubscriptionDelete, handler)
}

func (c *Client) OnTypingStart(handler func(c *Client, p payloads.TypingStart)) {
	On(c, dsevents.TypingStart, handler)
}

func (c *Client) OnUserUpdate(handler func(c *Client, p payloads.UserUpdate)) {
	On(c, dsevents.UserUpdate, handler)
}

func (c *Client) OnVoiceChannelEffectSend(handler func(c *Client, p payloads.VoiceChannelEffectSend)) {
	On(c, dsevents.VoiceChannelEffectSend, handler)
}

func (c *Client) OnVoiceChannelStartTimeUpdate(handler func(c *Client, p payloads.VoiceChannelStartTimeUpdate)) {
	On(c, dsevents.VoiceChannelStartTimeUpdate, handler)
}

func (c *Client) OnVoiceStateUpdate(handler func(c *Client, p payloads.VoiceStateUpdate)) {
	On(c, dsevents.VoiceStateUpdate, handler)
}

func (c *Client) OnVoiceServerUpdate(handler func(c *Client, p payloads.VoiceServerUpdate)) {
	On(c, dsevents.VoiceServerUpdate, handler)
}

func (c *Client) OnWebhooksUpdate(handler func(c *Client, p payloads.WebhooksUpdate)) {
	On(c, dsevents.WebhooksUpdate, handler)
}

func (c *Client) OnMessagePollVoteAdd(handler func(c *Client, p payloads.MessagePollVoteAdd)) {
	On(c, dsevents.MessagePollVoteAdd, handler)
}

func (c *Client) OnMessagePollVoteRemove(handler func(c *Client, p payloads.MessagePollVoteRemove)) {
	On(c, dsevents.MessagePollVoteRemove, handler)
}

