services:
  postgres:
    image: postgres:16
    container_name: camilla-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    ports:
      - "2323:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWD}
    ports:
      - "5423:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
