//go:build ignore

package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
	"text/template"
)

type Event struct {
	Method  string // OnMessageCreate
	Payload string // MessageCreate
	Const   string // events.MessageCreate
}

func screamingSnakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
	}
	return strings.Join(parts, "")
}

var tmpl = template.Must(template.New("").Parse(`// Code generated by go generate. DO NOT EDIT.
package gateway

import "cynthia/ds/payloads"
import "cynthia/ds/dsevents"

{{range .}}
func (c *Client) {{.Method}}(handler func(c *Client, p payloads.{{.Payload}})) {
	On(c, {{.Const}}, handler)
}
{{end}}
`))

func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "../../ds/dsevents/names.go", nil, 0)
	if err != nil {
		panic(err)
	}

	var evts []Event
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}
		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for _, name := range valueSpec.Names {
				constName := name.String() // e.g. "MessageCreate"
				// Extract the string value e.g. "MESSAGE_CREATE"
				lit, ok := valueSpec.Values[0].(*ast.BasicLit)
				if !ok {
					continue
				}
				rawVal := strings.Trim(lit.Value, `"`)   // MESSAGE_CREATE
				pascal := screamingSnakeToPascal(rawVal) // MessageCreate
				evts = append(evts, Event{
					Method:  "On" + constName,
					Payload: pascal,
					Const:   "dsevents." + constName,
				})
			}
		}
	}

	out, err := os.Create("handlers-gen.go")
	if err != nil {
		panic(err)
	}
	defer out.Close()

	if err := tmpl.Execute(out, evts); err != nil {
		panic(err)
	}
}
